Fix Maven Plugin warning of not using provided scope
plexus-utils is required for the org.codehaus.plexus.util.DirectoryScanner

plexus-xml is required for the MavenJupiterExtension, if not provided it causes a
java.lang.NoClassDefFoundError: org/codehaus/plexus/util/xml/pull/XmlPullParserException